// Generated by png2c [(c) Oleg Vaskevich 2013]

#ifndef _sounder_active_H_
#define _sounder_active_H_

extern const unsigned int sounder_active_width;
extern const unsigned int sounder_active_height;
extern const int sounder_active_size;
extern const unsigned short sounder_active[];

#endif

